version: "3.0"


networks: 
  one_full_net:
    external: true

services:
  node:
    build: 
      context: ./node
    volumes:
      - ${DATA_HOST}:/usr/src/projects
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
      - 9528:9528
    networks:
      - one_full_net