version: "3.8"

services:
  # EMQX
  emqx:
    image: emqx/emqx:${EMQX_VERSION}
    restart: always
    ports:
      - 1883:1883
      - 18083:18083
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=node1.emqx.iot
      - EMQX_CLUSTER__DISCOVERY=static
      - EMQX_CLUSTER__STATIC__SEEDS=emqx@node1.emqx.iot
      - EMQX_LISTENER__TCP__INTERNAL=0.0.0.0:11883
    volumes:
      - ./emqx_dashboard.conf:/opt/emqx/etc/plugins/emqx_dashboard.conf
      - ./acl.conf:/opt/emqx/etc/acl.conf
      - ./loaded_plugins:/opt/emqx/data/loaded_plugins
      - ./loaded_modules:/opt/emqx/data/loaded_modules
    healthcheck:
      test: [ "CMD", "/opt/emqx/bin/emqx_ctl", "status" ]
      interval: 5s
      timeout: 25s
      retries: 5
    networks:
      default:
        aliases:
          - node1.emqx.iot
