version: '3.4'

services:
  neuronex:
    image: emqx/neuronex:latest
    container_name: neuronex
    ports:
    - "7000:7000"
    restart: always
    privileged: true
    volumes:
      - ./data/data:/opt/neuron/persistence
      - ./data/log:/opt/neuron/logs
      # - ./data/plugins:/opt/neuron/plugins