version: "3.8"
services:
  #Service for nameserver
  namesrv:
    ## 请注意构建镜像的镜像名(apacherocketmq/rocketmq)与使用dockerhub的不同 
    image: apache/rocketmq:${ROCKETMQ_VERSION}
    container_name: rocketmq-namesrv
    restart: always
    ports:
      - 9876:9876
    volumes:
      - ./data/namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv

  #Service for broker1
  broker1:
    image: apache/rocketmq:${ROCKETMQ_VERSION}
    container_name: rocketmq-broker-1
    restart: always
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    depends_on:
      - namesrv
    environment:
      - NAMESRV_ADDR=namesrv:9876
      - BROKER_IP1=${ROCKETMQ_BROKER_IP1}
      - BROKER_LISTEN_PORT=10911
      - BROKER_NAME=rocketmq-broker-1
      - BROKER_ID=0
      - BROKER_ROLE=ASYNC_MASTER
      - BROKER_CLUSTER_NAME=${BROKER_CLUSTER_NAME}
    volumes:
      - ./data/broker1/logs:/home/rocketmq/logs
      - ./data/broker1/store:/home/rocketmq/store
      - ./broker.conf:/opt/rocketmq-${ROCKETMQ_VERSION}/conf/default.conf
      - ./start-broker.sh:/home/rocketmq/rocketmq-${ROCKETMQ_VERSION}/bin/start-broker.sh
    command: sh start-broker.sh


  #Service for another broker2
  broker2:
    image: apache/rocketmq:${ROCKETMQ_VERSION}
    container_name: rocketmq-broker-2
    restart: always
    ports:
      - 10929:10909
      - 10931:10931
      - 10932:10912
    depends_on:
      - namesrv
    environment:
      - NAMESRV_ADDR=namesrv:9876
      - BROKER_IP1=${ROCKETMQ_BROKER_IP1}
      - BROKER_LISTEN_PORT=10931
      - BROKER_NAME=rocketmq-broker-2
      - BROKER_ID=0
      - BROKER_ROLE=ASYNC_MASTER
      - BROKER_CLUSTER_NAME=${BROKER_CLUSTER_NAME}
    volumes:
      - ./data/broker2/logs:/home/rocketmq/logs
      - ./data/broker2/store:/home/rocketmq/store
      - ./broker.conf:/opt/rocketmq-${ROCKETMQ_VERSION}/conf/default.conf
      - ./start-broker.sh:/home/rocketmq/rocketmq-${ROCKETMQ_VERSION}/bin/start-broker.sh
    command: sh start-broker.sh
  dashboard:
    image: apacherocketmq/rocketmq-dashboard:${ROCKETMQ_DASHBOARD_VERSION}
    container_name: rocketmq-dashboard
    restart: always
    ports:
      - 8076:8080
    depends_on:
      - namesrv
    environment:
      - "JAVA_OPTS= -Drocketmq.namesrv.addr=namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
