version: '3.8'


services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: jetlinks-rabbitmq
    volumes:
        - ./data/rabbitmq/data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - "15672:15672"
      - "5672:5672"