version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_DOMAIN_NAME}'
        nginx['listen_port'] = 80
        nginx['custom_gitlab_server_config'] = "set_real_ip_from 172.0.0.0/8;\nreal_ip_header X-Real-IP;\nreal_ip_recursive on;"
        gitlab_rails['initial_root_password'] = '${GITLAB_ROOT_PASSWORD}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_HOST_SSH_PORT}
        gitlab_rails['time_zone'] = '${GITLAB_TZ}'
    volumes:
      - ./data/gitlab/config:/etc/gitlab
      - ./data/gitlab/data:/var/opt/gitlab
      - ./data/gitlab/logs:/var/log/gitlab
    ports:
      - "${GITLAB_HOST_HTTP_PORT}:80"
      - "${GITLAB_HOST_HTTPS_PORT}:443"
      - "${GITLAB_HOST_SSH_PORT}:22"
  # 不可用
  # gitlab-runner:
  #   image: gitlab/gitlab-runner:latest
  #   environment:
  #     - CI_SERVER_URL=${GITLAB_CI_SERVER_URL}
  #     - REGISTRATION_TOKEN=${GITLAB_RUNNER_REGISTRATION_TOKEN}
  #     - RUNNER_NAME=gitlab-runner
  #     - REGISTER_NON_INTERACTIVE=${GITLAB_REGISTER_NON_INTERACTIVE}
  #     - RUNNER_EXECUTOR=shell
  #   volumes:
  #     - ./data/gitlab/runner:/etc/gitlab-runner
  #     - /var/run/docker.sock:/var/run/docker.sock:rw
  #   restart: always