version: '3.8'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch1:9200","http://elasticsearch2:9200","http://elasticsearch3:9200"]'
      I18N_LOCALE: zh-CN
    # volumes:
    #     - ../data/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    container_name: elasticsearch1
    environment:
      - node.name=elasticsearch1
      - cluster.name=es-cluster
      - discovery.seed_hosts=elasticsearch1,elasticsearch2,elasticsearch3
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es-cluster/node1/data:/usr/share/elasticsearch/data
      - ./data/es-cluster/node1/logs:/usr/share/elasticsearch/logs
      - ./data/es-cluster/plugins:/usr/share/elasticsearch/plugins
    ports:
      - 9200:9200
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    container_name: elasticsearch2
    environment:
      - node.name=elasticsearch2
      - cluster.name=es-cluster
      - discovery.seed_hosts=elasticsearch1,elasticsearch2,elasticsearch3
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es-cluster/node2/data:/usr/share/elasticsearch/data
      - ./data/es-cluster/node2/logs:/usr/share/elasticsearch/logs
      - ./data/es-cluster/plugins:/usr/share/elasticsearch/plugins
    ports:
      - 9300:9200
  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    container_name: elasticsearch3
    environment:
      - node.name=elasticsearch3
      - cluster.name=es-cluster
      - discovery.seed_hosts=elasticsearch1,elasticsearch2,elasticsearch3
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es-cluster/node3/data:/usr/share/elasticsearch/data
      - ./data/es-cluster/node3/logs:/usr/share/elasticsearch/logs
      - ./data/es-cluster/plugins:/usr/share/elasticsearch/plugins
    ports:
      - 9400:9200

 
