version: "3.8"

networks:
  iotdb:
    external: true

services:
  backend:
    build: .
    restart: always
    ports:
      - 7665:9090  #访问端口
    volumes:
      - ./data/backend/iotdb.db:/data/iotdb.db #数据库挂载前面为本地路径
    working_dir: /app
    environment:
      spring.datasource.url: jdbc:sqlite:/data/iotdb.db
      TZ: Asia/Shanghai
    networks:
      iotdb: 
          ipv4_address: 172.25.0.10
      default: