version: "3.0"

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "50001:8080"
      - "50000:50000"
