version: '3.7'
 
services:
  tdengine:
    image: tdengine/tdengine:2.4.0.3
    container_name: tdengine
    hostname: tdengine
    cap_add:
      - ALL
    ports:
      - "6030-6041:6030-6041"
      # 外部连接不仅要放通TCP,还要放通UDP
      - "6030-6041:6030-6041/udp"
    volumes:
      - ./cfg/taos.cfg:/etc/taos/taos.cfg
      - ./data/tdengine/log:/var/log/taos
      - ./data/tdengine/data:/var/lib/taos
    environment:
      TZ: Asia/Shanghai
    restart: always

