version: '3.4'

services:
  manager:
    image: emqx/ekuiper-manager:latest
    container_name: ekuiper-manager
    ports:
    - "9082:9082"
    restart: unless-stopped
    environment: 
      # setting default eKuiper service, works since 1.8.0
      DEFAULT_EKUIPER_ENDPOINT: "http://ekuiper:9081"
  ekuiper:
    image: lfedge/ekuiper:latest
    ports:
      - "9081:9081"
      - "127.0.0.1:20498:20498"
    container_name: ekuiper
    hostname: ekuiper
    restart: unless-stopped
    user: root
    volumes:
      - ./data/data:/kuiper/data
      - ./data/log:/kuiper/log
      # - ./data/plugins:/kuiper/plugins
    environment:
      MQTT_SOURCE__DEFAULT__SERVER: "tcp://broker.emqx.io:1883"
      KUIPER__BASIC__CONSOLELOG: "true"
      KUIPER__BASIC__IGNORECASE: "false"