version: '3.7'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    volumes:
      - ./data/zookeeper/data:/data
    ports:
      - "2181:2181"
    restart: always
  kafka1:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - ./data/kafka/node_1/data:/kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INSIDE://:19092,OUTSIDE://:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:19092,OUTSIDE://${KAFKA_HOSTNAME}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      JMX_PORT: 9999
    restart: always
  kafka2:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    volumes:
      - ./data/kafka/node_2/data:/kafka
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: INSIDE://:19093,OUTSIDE://:9093
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka2:19093,OUTSIDE://${KAFKA_HOSTNAME}:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      JMX_PORT: 9999
    restart: always
  kafka3:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    volumes:
      - ./data/kafka/node_3/data:/kafka
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: INSIDE://:19094,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka3:19094,OUTSIDE://${KAFKA_HOSTNAME}:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      JMX_PORT: 9999
    restart: always

  kafka-manager:
    # 使用该管理
    image: kafkamanager/kafka-manager
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: "zookeeper:2181"
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
      - kafka3
    restart: always
