version: '3'

services:
  zookeeper:
    image: 'bitnami/zookeeper:${ZOOKEEPER_VERSION}'
    volumes:
      - ./data/zookeeper/data:/bitnami/zookeeper
    ports:
      - "2181:2181"
    restart: always
    environment:
      ZOO_ENABLE_AUTH: yes
      ZOO_SERVER_USERS: ${ZOOKEEPER_USER}
      ZOO_SERVER_PASSWORDS: ${ZOOKEEPER_PASSWORD}
      ZOO_CLIENT_USER: ${ZOOKEEPER_USER}
      ZOO_CLIENT_PASSWORD: ${ZOOKEEPER_PASSWORD}
  kafka1:
    image: 'bitnami/kafka:${KAFKA_VERSION}'
    ports:
      - "9092:9092"
      - "9992:9992"
      - "19092:19092"
    restart: always
    volumes:
      - ./data/kafka/node_1/data:/bitnami/kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: INSIDE://:19092,OUTSIDE://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: INSIDE://${KAFKA_HOSTNAME}:19092,OUTSIDE://${KAFKA_HOSTNAME}:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INSIDE
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_PROTOCOL: SASL
      KAFKA_ZOOKEEPER_USER: ${ZOOKEEPER_USER}
      KAFKA_ZOOKEEPER_PASSWORD: ${ZOOKEEPER_PASSWORD}
      JMX_PORT: 9992
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=9992 -Djava.rmi.server.hostname=${KAFKA_HOSTNAME}


  kafka2:
    image: 'bitnami/kafka:${KAFKA_VERSION}'
    ports:
      - "9093:9093"
      - "9993:9993"
      - "19093:19093"
    restart: always
    volumes:
      - ./data/kafka/node_2/data:/bitnami/kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_CFG_LISTENERS: INSIDE://:19093,OUTSIDE://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: INSIDE://${KAFKA_HOSTNAME}:19093,OUTSIDE://${KAFKA_HOSTNAME}:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INSIDE
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_PROTOCOL: SASL
      KAFKA_ZOOKEEPER_USER: ${ZOOKEEPER_USER}
      KAFKA_ZOOKEEPER_PASSWORD: ${ZOOKEEPER_PASSWORD}
      JMX_PORT: 9993
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=9993 -Djava.rmi.server.hostname=${KAFKA_HOSTNAME}

  kafka3:
    image: 'bitnami/kafka:${KAFKA_VERSION}'
    ports:
      - "9094:9094"
      - "9994:9994"
      - "19094:19094"
    restart: always
    volumes:
      - ./data/kafka/node_3/data:/bitnami/kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_CFG_LISTENERS: INSIDE://:19094,OUTSIDE://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: INSIDE://${KAFKA_HOSTNAME}:19094,OUTSIDE://${KAFKA_HOSTNAME}:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INSIDE
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_PROTOCOL: SASL
      KAFKA_ZOOKEEPER_USER: ${ZOOKEEPER_USER}
      KAFKA_ZOOKEEPER_PASSWORD: ${ZOOKEEPER_PASSWORD}
      JMX_PORT: 9994
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=9994 -Djava.rmi.server.hostname=${KAFKA_HOSTNAME}