version: "3"
services:
  iotdb-standalone:
    image: apache/iotdb:1.0.0-standalone
    hostname: iotdb-standalone
    container_name: iotdb-standalone
    ports:
      - "6667:6667"
    environment:
      - cn_internal_address=iotdb-standalone
      - cn_target_config_node_list=iotdb-standalone:22277
      - dn_rpc_address=0.0.0.0
      - dn_target_config_node_list=iotdb-standalone:22277
    volumes:
        - ./data/standalone/data:/iotdb/data
        - ./data/standalone/logs:/iotdb/logs
    networks:
      iotdb:
        ipv4_address: 172.25.0.6

networks:
  iotdb:
    external: true